In [16]:
import pandas as pd

df = pd.read_csv("../data/raw/qualified_leads.csv")
df.head()

,mql_id,first_contact_date,landing_page_id,origin
0,dac32acd4db4c29c230538b72f8dd87d,2018-02-01,88740e65d5d6b056e0cda098e1ea6313,social
1,8c18d1de7f67e60dbd64e3c07d7e9d5d,2017-10-20,007f9098284a86ee80ddeb25d53e0af8,paid_search
2,b4bc852d233dfefc5131f593b538befa,2018-03-22,a7982125ff7aa3b2054c6e44f9d28522,organic_search
3,6be030b81c75970747525b843c1ef4f8,2018-01-22,d45d558f0daeecf3cccdffe3c59684aa,email
4,5420aad7fec3549a85876ba1c529bd84,2018-02-21,b48ec5f3b04e9068441002a19df93c6c,organic_search

In [17]:
# INVESTIGAR QUALIDADE DOS DADOS 
df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   mql_id              8000 non-null   object
 1   first_contact_date  8000 non-null   object
 2   landing_page_id     8000 non-null   object
 3   origin              7940 non-null   object
dtypes: object(4)
memory usage: 250.1+ KB

mql_id                 0
first_contact_date     0
landing_page_id        0
origin                60
dtype: int64

In [18]:
# VERIFICAR DUPLICATOS POR LINHAS

df.duplicated().sum()

np.int64(0)

In [19]:
# MODIFICAR TYPE COLUNA DATE

df['first_contact_date'] = pd.to_datetime(df['first_contact_date'])

#VALIDAR CHANGE
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   mql_id              8000 non-null   object
 1   first_contact_date  8000 non-null   datetime64[ns]
 2   landing_page_id     8000 non-null   object
 3   origin              7940 non-null   object
dtypes: datetime64[ns](1), object(3)
memory usage: 250.1+ KB

,mql_id,first_contact_date,landing_page_id,origin
0,dac32acd4db4c29c230538b72f8dd87d,2018-02-01,88740e65d5d6b056e0cda098e1ea6313,social
1,8c18d1de7f67e60dbd64e3c07d7e9d5d,2017-10-20,007f9098284a86ee80ddeb25d53e0af8,paid_search
2,b4bc852d233dfefc5131f593b538befa,2018-03-22,a7982125ff7aa3b2054c6e44f9d28522,organic_search
3,6be030b81c75970747525b843c1ef4f8,2018-01-22,d45d558f0daeecf3cccdffe3c59684aa,email
4,5420aad7fec3549a85876ba1c529bd84,2018-02-21,b48ec5f3b04e9068441002a19df93c6c,organic_search

In [20]:
df['origin'].unique()

# TRATAR VALORES NULOS DA COLUNA ORIGIN

df['origin'] = df['origin'].fillna('unknown')

# VALIDAR

df['origin'].isnull().sum()

np.int64(0)

In [21]:
#EXPORTACAO DOS DADOS TRATADOS PARA A CAMADA SILVER


df.to_csv(
    "../data/silver/qualified_leads_clean.csv",
    index=False
)